# -*- coding: utf-8 -*-
"""
YAMNetクラス名の日本語対訳辞書
"""

YAMNET_JAPANESE_CLASSES = {
    "Speech": "人の話し声",
    "Male speech, man speaking": "男性の話し声",
    "Female speech, woman speaking": "女性の話し声", 
    "Child speech, kid speaking": "子供の話し声",
    "Conversation": "会話",
    "Narration, monologue": "ナレーション・独白",
    "Babbling": "赤ちゃんの声",
    "Shout": "叫び声",
    "Bellow": "怒鳴り声",
    "Whoop": "歓声",
    "Yell": "大声",
    "Battle cry": "雄叫び",
    "Children shouting": "子供の叫び声",
    "Screaming": "悲鳴",
    "Whispering": "ささやき声",
    "Laughter": "笑い声",
    "Baby laughter": "赤ちゃんの笑い声",
    "Giggle": "くすくす笑い",
    "Snicker": "忍び笑い",
    "Belly laugh": "腹を抱えて笑う",
    "Chuckle, chortle": "クスクス笑い",
    "Crying, sobbing": "泣き声・すすり泣き",
    "Baby cry, infant cry": "赤ちゃんの泣き声",
    "Whimper": "すすり泣き",
    "Wail, moan": "嘆き・うめき声",
    "Sigh": "ため息",
    "Singing": "歌声",
    "Choir": "合唱",
    "Yodeling": "ヨーデル",
    "Chant": "詠唱",
    "Mantra": "マントラ",
    "Male singing": "男性の歌声",
    "Female singing": "女性の歌声",
    "Child singing": "子供の歌声",
    "Synthetic singing": "合成歌声",
    "Rapping": "ラップ",
    "Humming": "鼻歌",
    "Groan": "うめき声",
    "Grunt": "うなり声",
    "Whistling": "口笛",
    "Breathing": "呼吸音",
    "Wheeze": "ぜいぜい音",
    "Snoring": "いびき",
    "Gasp": "息を呑む音",
    "Pant": "はぁはぁという息",
    "Snort": "鼻を鳴らす音",
    "Cough": "咳",
    "Throat clearing": "咳払い",
    "Sneeze": "くしゃみ",
    "Sniff": "鼻をすする音",
    "Run": "走る音",
    "Shuffle": "すり足",
    "Walk, footsteps": "歩く音・足音",
    "Chewing, mastication": "咀嚼音",
    "Biting": "噛む音",
    "Gargling": "うがいの音",
    "Stomach rumble": "お腹の音",
    "Burping, eructation": "げっぷ",
    "Hiccup": "しゃっくり",
    "Fart": "おなら",
    "Hands": "手の音",
    "Finger snapping": "指を鳴らす音",
    "Clapping": "拍手",
    "Heart sounds, heartbeat": "心音・心拍",
    "Heart murmur": "心雑音",
    "Cheering": "応援",
    "Applause": "拍手喝采",
    "Chatter": "おしゃべり",
    "Crowd": "群衆",
    "Hubbub, speech noise, speech babble": "ざわめき・話し声の雑音",
    "Children playing": "子供の遊び声",
    "Animal": "動物",
    "Domestic animals, pets": "ペット・家畜",
    "Dog": "犬",
    "Bark": "犬の鳴き声",
    "Yip": "犬の短い鳴き声",
    "Howl": "遠吠え",
    "Bow-wow": "ワンワン",
    "Growling": "うなり声",
    "Whimper (dog)": "犬のクンクン声",
    "Cat": "猫",
    "Purr": "猫のゴロゴロ",
    "Meow": "ニャーオ",
    "Hiss": "シューッという音",
    "Caterwaul": "猫の鳴き声",
    "Livestock, farm animals, working animals": "家畜・農場動物",
    "Horse": "馬",
    "Clip-clop": "馬の蹄の音",
    "Neigh, whinny": "馬のいななき",
    "Cattle, bovines": "牛",
    "Moo": "牛の鳴き声（モー）",
    "Cowbell": "カウベル",
    "Pig": "豚",
    "Oink": "豚の鳴き声（ブーブー）",
    "Goat": "ヤギ",
    "Bleat": "ヤギ・羊の鳴き声",
    "Sheep": "羊",
    "Fowl": "家禽",
    "Chicken, rooster": "鶏",
    "Cluck": "鶏のコッコッ声",
    "Crowing, cock-a-doodle-doo": "雄鶏の鳴き声（コケコッコー）",
    "Turkey": "七面鳥",
    "Gobble": "七面鳥の鳴き声",
    "Duck": "アヒル",
    "Quack": "アヒルの鳴き声（ガーガー）",
    "Goose": "ガチョウ",
    "Honk": "ガチョウの鳴き声",
    "Wild animals": "野生動物",
    "Roaring cats (lions, tigers)": "大型ネコ科（ライオン・トラ）",
    "Roar": "吠える・うなる",
    "Bird": "鳥",
    "Bird vocalization, bird call, bird song": "鳥の鳴き声",
    "Chirp, tweet": "チーチー・ピーピー",
    "Squawk": "鳥の鳴き声",
    "Pigeon, dove": "ハト",
    "Coo": "ハトの鳴き声（ポッポ）",
    "Crow": "カラス",
    "Caw": "カラスの鳴き声（カーカー）",
    "Owl": "フクロウ",
    "Hoot": "フクロウの鳴き声（ホーホー）",
    "Bird flight, flapping wings": "鳥の羽ばたき",
    "Canidae, dogs, wolves": "イヌ科",
    "Rodents, rats, mice": "齧歯類・ネズミ",
    "Mouse": "ネズミ",
    "Patter": "小刻みな音",
    "Insect": "昆虫",
    "Cricket": "コオロギ",
    "Mosquito": "蚊",
    "Fly, housefly": "ハエ",
    "Buzz": "ブンブン・ブザー音",
    "Bee, wasp, etc.": "ハチ・スズメバチなど",
    "Frog": "カエル",
    "Croak": "カエルの鳴き声（ケロケロ）",
    "Snake": "ヘビ",
    "Rattle": "ガラガラヘビの音",
    "Whale vocalization": "クジラの鳴き声",
    "Music": "音楽",
    "Musical instrument": "楽器",
    "Plucked string instrument": "弦楽器（弾く）",
    "Guitar": "ギター",
    "Electric guitar": "エレキギター",
    "Bass guitar": "ベースギター",
    "Acoustic guitar": "アコースティックギター",
    "Steel guitar, slide guitar": "スチールギター・スライドギター",
    "Tapping (guitar technique)": "タッピング（ギター奏法）",
    "Strum": "ストローク",
    "Banjo": "バンジョー",
    "Sitar": "シタール",
    "Mandolin": "マンドリン",
    "Zither": "ツィター",
    "Ukulele": "ウクレレ",
    "Keyboard (musical)": "キーボード",
    "Piano": "ピアノ",
    "Electric piano": "エレクトリックピアノ",
    "Honky-tonk piano": "ホンキートンクピアノ",
    "Piano roll": "ピアノロール",
    "Harpsichord": "ハープシコード",
    "Pipe organ": "パイプオルガン",
    "Hammond organ": "ハモンドオルガン",
    "Synthesizer": "シンセサイザー",
    "Sampler": "サンプラー",
    "Percussion": "打楽器",
    "Drum kit": "ドラムセット",
    "Drum machine": "ドラムマシン",
    "Drum": "ドラム",
    "Snare drum": "スネアドラム",
    "Rimshot": "リムショット",
    "Drum roll": "ドラムロール",
    "Bass drum": "バスドラム",
    "Timpani": "ティンパニ",
    "Tabla": "タブラ",
    "Cymbal": "シンバル",
    "Hi-hat": "ハイハット",
    "Wood block": "ウッドブロック",
    "Tambourine": "タンバリン",
    "Rattle (instrument)": "ラトル（楽器）",
    "Maraca": "マラカス",
    "Gong": "ゴング",
    "Tubular bells": "チューブラーベル",
    "Mallet percussion": "マレット打楽器",
    "Marimba, xylophone": "マリンバ・木琴",
    "Glockenspiel": "グロッケンシュピール",
    "Vibraphone": "ヴィブラフォン",
    "Steelpan": "スチールパン",
    "Orchestra": "オーケストラ",
    "Brass instrument": "金管楽器",
    "French horn": "ホルン",
    "Trumpet": "トランペット",
    "Trombone": "トロンボーン",
    "Bugle": "ビューグル",
    "Cornet": "コルネット",
    "Saxophone": "サクソフォン",
    "Soprano saxophone": "ソプラノサックス",
    "Alto saxophone": "アルトサックス",
    "Tenor saxophone": "テナーサックス",
    "Baritone saxophone": "バリトンサックス",
    "Oboe": "オーボエ",
    "Flute": "フルート",
    "Recorder": "リコーダー",
    "Piccolo": "ピッコロ",
    "Wind instrument, woodwind instrument": "管楽器・木管楽器",
    "Shofar": "ショファール",
    "Clarinet": "クラリネット",
    "Harp": "ハープ",
    "Bell": "ベル・鐘",
    "Church bell": "教会の鐘",
    "Jingle bell": "ジングルベル",
    "Bicycle bell": "自転車のベル",
    "Tuning fork": "音叉",
    "Chime": "チャイム",
    "Wind chime": "風鈴",
    "Change ringing (campanology)": "変化鐘（カンパノロジー）",
    "Harmonica": "ハーモニカ",
    "Accordion": "アコーディオン",
    "Bagpipes": "バグパイプ",
    "Fiddle, violin": "バイオリン",
    "Pizzicato": "ピッツィカート",
    "Bowed string instrument": "弓弦楽器",
    "String section": "弦楽セクション",
    "Viola": "ヴィオラ",
    "Cello": "チェロ",
    "Double bass": "コントラバス",
    "Electric violin": "エレクトリックバイオリン",
    "Funk": "ファンク",
    "Reggae": "レゲエ",
    "Pop music": "ポップ音楽",
    "Hip hop music": "ヒップホップ音楽",
    "Beatboxing": "ビートボックス",
    "Rock music": "ロック音楽",
    "Heavy metal": "ヘビーメタル",
    "Punk rock": "パンクロック",
    "Grunge": "グランジ",
    "Progressive rock": "プログレッシブロック",
    "Rock and roll": "ロックンロール",
    "Psychedelic rock": "サイケデリックロック",
    "Rhythm and blues": "リズム&ブルース",
    "Soul music": "ソウル音楽",
    "Country": "カントリー音楽",
    "Bluegrass": "ブルーグラス",
    "Flamenco": "フラメンコ",
    "Folk music": "フォーク音楽",
    "Middle Eastern music": "中東音楽",
    "Jazz": "ジャズ",
    "Disco": "ディスコ",
    "Classical music": "クラシック音楽",
    "Opera": "オペラ",
    "Electronic music": "エレクトロニック音楽",
    "House music": "ハウス音楽",
    "Techno": "テクノ",
    "Dubstep": "ダブステップ",
    "Drum and bass": "ドラムンベース",
    "Electronica": "エレクトロニカ",
    "Electronic dance music": "EDM",
    "Ambient music": "アンビエント音楽",
    "Trance music": "トランス音楽",
    "Music of Latin America": "ラテン音楽",
    "Salsa music": "サルサ音楽",
    "Blues": "ブルース",
    "Music for children": "子供向け音楽",
    "New-age music": "ニューエイジ音楽",
    "Vocal music": "声楽",
    "A capella": "アカペラ",
    "Music of Africa": "アフリカ音楽",
    "Afrobeat": "アフロビート",
    "Christian music": "クリスチャン音楽",
    "Gospel music": "ゴスペル音楽",
    "Music of Asia": "アジア音楽",
    "Carnatic music": "カルナティック音楽",
    "Music of Bollywood": "ボリウッド音楽",
    "Sound effect": "効果音",
    "Single-lens reflex camera": "一眼レフカメラ",
    "Tools": "道具",
    "Hammer": "ハンマー",
    "Wood": "木",
    "Sawing": "のこぎり",
    "Filing (rasp)": "やすりがけ",
    "Sanding": "サンドペーパー",
    "Power tool": "電動工具",
    "Jackhammer": "削岩機",
    "Drilling": "ドリル",
    "Explosion": "爆発",
    "Gunshot, gunfire": "銃声",
    "Machine gun": "機関銃",
    "Fusillade": "一斉射撃",
    "Artillery fire": "大砲の発砲",
    "Cap gun": "おもちゃの銃",
    "Fireworks": "花火",
    "Firecracker": "爆竹",
    "Burst, pop": "破裂音・ポン",
    "Eruption": "噴火",
    "Boom": "ドーン",
    "Chop": "たたき切る音",
    "Splinter": "木片の音",
    "Crack": "ひび割れ音",
    "Glass": "ガラス",
    "Chink, clink": "チンという音",
    "Shatter": "粉々に砕ける音",
    "Liquid": "液体",
    "Splash, splatter": "飛沫・しぶき",
    "Slosh": "液体が揺れる音",
    "Squish": "ぐちゃぐちゃ音",
    "Drip": "しずく",
    "Pour": "注ぐ音",
    "Trickle, dribble": "したたる音",
    "Gush": "激流",
    "Fill (with liquid)": "液体で満たす",
    "Spray": "スプレー",
    "Pump (liquid)": "液体ポンプ",
    "Stir": "かき混ぜる",
    "Boiling": "沸騰",
    "Sonar": "ソナー",
    "Water": "水",
    "Stream": "小川",
    "Waterfall": "滝",
    "Ocean": "海",
    "Waves, surf": "波",
    "Steam": "蒸気",
    "Toilet flush": "トイレの水流",
    "Faucet, tap": "蛇口",
    "Sink (filling or washing)": "流し台",
    "Bathtub (filling or washing)": "浴槽",
    "Hair dryer": "ヘアドライヤー",
    "Water tap, faucet": "水道の蛇口",
    "Mechanisms": "機械",
    "Ratchet, pawl": "ラチェット",
    "Clock": "時計",
    "Tick": "チクタク",
    "Tick-tock": "チクタク",
    "Metronome": "メトロノーム",
    "Pendulum": "振り子",
    "Swing (motion)": "振れる音",
    "Door": "ドア",
    "Sliding door": "引き戸",
    "Slam": "バタンと閉じる音",
    "Knock": "ノック",
    "Tap": "軽く叩く音",
    "Squeak": "きしみ音",
    "Cupboard open or close": "食器棚の開閉",
    "Drawer open or close": "引き出しの開閉",
    "Dishes, pots, and pans": "食器・鍋類",
    "Cutlery, silverware": "カトラリー",
    "Chopping (food)": "食材を切る音",
    "Frying (food)": "炒める音",
    "Microwave oven": "電子レンジ",
    "Blender": "ミキサー",
    "Water boiling": "湯沸かし",
    "Sizzle": "ジューという音",
    "Baking": "焼く音",
    "Opening or closing": "開閉",
    "Motorcycle": "オートバイ",
    "Traffic noise, roadway noise": "交通騒音・道路騒音",
    "Rail transport": "鉄道",
    "Train": "電車",
    "Train whistle": "電車の汽笛",
    "Train horn": "電車のホーン",
    "Railroad car, train wagon": "鉄道車両",
    "Train wheels squealing": "電車の車輪の軋み音",
    "Subway, metro, underground": "地下鉄",
    "Aircraft": "航空機",
    "Aircraft engine": "航空機エンジン",
    "Jet engine": "ジェットエンジン",
    "Propeller, airscrew": "プロペラ",
    "Helicopter": "ヘリコプター",
    "Fixed-wing aircraft, airplane": "固定翼機・飛行機",
    "Bicycle": "自転車",
    "Skateboard": "スケートボード",
    "Engine": "エンジン",
    "Light engine (high frequency)": "軽エンジン（高周波）",
    "Dental drill, dentist's drill": "歯科用ドリル",
    "Lawn mower": "芝刈り機",
    "Chainsaw": "チェーンソー",
    "Medium engine (mid frequency)": "中型エンジン（中周波）",
    "Heavy engine (low frequency)": "重エンジン（低周波）",
    "Engine knocking": "エンジンノッキング",
    "Engine starting": "エンジン始動",
    "Idling": "アイドリング",
    "Accelerating, revving, vroom": "加速・空吹かし",
    "Door of car": "車のドア",
    "Car passing by": "車の通過音",
    "Race car, auto racing": "レースカー・自動車レース",
    "Truck": "トラック",
    "Air brake": "エアブレーキ",
    "Air horn, truck horn": "エアホーン・トラックホーン",
    "Reversing beeps": "バック音",
    "Ice cream truck, ice cream van": "アイスクリーム車",
    "Bus": "バス",
    "Emergency vehicle": "緊急車両",
    "Police car (siren)": "パトカー（サイレン）",
    "Ambulance (siren)": "救急車（サイレン）",
    "Fire engine, fire truck (siren)": "消防車（サイレン）",
    "Boat, Water vehicle": "船・水上車両",
    "Sailboat, sailing ship": "帆船",
    "Rowboat, canoe, kayak": "手漕ぎボート・カヌー・カヤック",
    "Motorboat, speedboat": "モーターボート・スピードボート",
    "Ship": "船",
    "Motor vehicle (road)": "自動車（道路）",
    "Car": "自動車",
    "Vehicle horn, car horn, honking": "車のクラクション",
    "Toot": "プー音",
    "Beep, bleep": "ビープ音",
    "Birdcall": "鳥の鳴き声",
    "Siren": "サイレン",
    "Civil defense siren": "防災サイレン",
    "Buzzer": "ブザー",
    "Smoke detector, smoke alarm": "煙探知器・火災報知器",
    "Alarm": "警報",
    "Alarm clock": "目覚まし時計",
    "Whistle": "笛",
    "Steam whistle": "蒸気笛",
    "Air horn, truck horn": "エアホーン",
    "Foghorn": "霧笛",
    "Car alarm": "車の盗難防止装置",
    "Power windows, electric windows": "パワーウインドウ",
    "Skidding": "スキッド音",
    "Tire squeal": "タイヤの軋み音",
    "Car doors": "車のドア",
    "Honking": "クラクション",
    "White noise": "ホワイトノイズ",
    "Pink noise": "ピンクノイズ",
    "Throbbing": "脈打つ音",
    "Vibration": "振動",
    "Television": "テレビ",
    "Radio": "ラジオ",
    "Field recording": "フィールドレコーディング",
    "Telephone": "電話",
    "Telephone bell ringing": "電話のベル",
    "Ringtone": "着信音",
    "Telephone dialing, DTMF": "電話のダイヤル・DTMF",
    "Dial tone": "発信音",
    "Busy signal": "話中音",
    "Inside, small room": "室内・小部屋",
    "Inside, large room or hall": "室内・大部屋またはホール",
    "Inside, public space": "室内・公共空間",
    "Outside, urban or manmade": "屋外・都市部・人工",
    "Outside, rural or natural": "屋外・田舎・自然",
    "Reverberation": "残響",
    "Echo": "エコー",
    "Noise": "ノイズ",
    "Environmental noise": "環境騒音",
    "Static": "静電気ノイズ",
    "Mains hum": "商用電源ハム音",
    "Distortion": "歪み",
    "Sidetone": "送話音",
    "Cacophony": "不協和音",
    "Silence": "無音"
}

def get_japanese_class_name(english_name):
    """英語クラス名を日本語に変換（辞書にない場合は英語のまま）"""
    return YAMNET_JAPANESE_CLASSES.get(english_name, english_name)